FROM python:3.12.3
WORKDIR /apps
COPY . /apps
RUN apt-get update && apt-get install -y python3 python3-pip
RUN pip install python-socketio
EXPOSE 12345
CMD ["python3", "Server_side_code.py"]

